// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mish10.Data;

#nullable disable

namespace Mish10.Migrations
{
    [DbContext(typeof(BowlingLeague3Context))]
    partial class BowlingLeague3ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");
#pragma warning restore 612, 618
        }
    }
}
